version: '3.8'
services:
  isb-api:
    build: .
    ports:
      - "80:4000"
      - "443:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always