version: '3.8'
services:
  isb-api:
    build: .
    ports:
      - "4000:4000"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always